name: streamlit_env
channels:
  - defaults
dependencies:
  - python=3.12.9
  - pip
  - pandas
  - numpy=1.26.4
  - seaborn
  - scikit-learn
  - streamlit
  - pip:
    - matplotlib
    - gitpython
    - pyarrow
    - joblib
    - contourpy
    - cycler
    - fonttools
    - pillow
    - pyparsing
    - protobuf
    - tenacity
    - watchdog
    - typing-extensions
